apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
        - name: wisecow
          image: raima01/wisecow:latest
          ports:
            - containerPort: 4499
          volumeMounts:
            - name: tls-secret
              mountPath: /app/tls
              readOnly: true
          args:
            - "--tls-cert"
            - "/app/tls/wisecow.crt"
            - "--tls-key"
            - "/app/tls/wisecow.key"
      volumes:
        - name: tls-secret
          secret:
            secretName: wisecow-tls
